### ISSUE TITLE
Count(): Parameter error... and fix.

### ISSUE THREAD

**Issue by magento-ralph** [ozh/ozh-admin-drop-down-menu#1]
Warning: count(): Parameter must be an array or an object that implements Countable in C:\Program Files\Ampps\www\myproject\wp-content\plugins\ozh-admin-drop-down-menu\inc\core.php on line 311

Original Code:
	if (!count($wp_ozh_adminmenu)) {
		$wp_ozh_adminmenu = (array)get_option('ozh_adminmenu');
		unset($wp_ozh_adminmenu[0]);
	}

Code Fix:
    if (!is_array($wp_ozh_adminmenu) || !count($wp_ozh_adminmenu)) {
        $wp_ozh_adminmenu = (array)get_option('ozh_adminmenu');
        unset($wp_ozh_adminmenu[0]);
    }

**Comment by ozh** [comment]
Thanks, I've updated the code here (this won't reflect on the official plugin repo though, I cba to reinstall SVN just for this)
