### ISSUE TITLE
Fix for Siteground's security plugin

### ISSUE THREAD

**Issue by phbyerly** [ozh/ozh-admin-drop-down-menu#18]
If fails to change to drop-down menus when either iThemes Security Pro or SiteGround Security are activated.

Please help!

**Comment by ozh** [comment]
"Not working" isn't of any help without details

**Comment by phbyerly** [comment]
If fails to change to drop-down menus when either iThemes Security Pro or SiteGround Security are activated.

![image](https://user-images.githubusercontent.com/111709826/187253199-ecfe77ee-b156-475d-a3ef-b4b5013373fe.png)

**Comment by phbyerly** [comment]
Follow up - it is the "Lock and Protect System Folders" that is breaking it.

**Comment by phbyerly** [comment]
Siteground provided a solution for their plugin. Add to the active theme's functions.php

`/** whitelist Ozh' Admin Drop Down Menu
*/
add_filter( 'sgs_whitelist_wp_content' , 'whitelist_file_in_wp_content' );
function whitelist_file_in_wp_content( $whitelist ) {
// $whitelist[] = 'plugins/ozh-admin-drop-down-menu/wp_ozh_adminmenu.php';
// $whitelist[] = 'plugins/ozh-admin-drop-down-menu/inc/adminmenu.css.php';
$whitelist[] = 'wp_ozh_adminmenu.php';
$whitelist[] = 'adminmenu.css.php';

return $whitelist;
}`

**Comment by ozh** [comment]
Thanks for reporting in
